version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/landscape
    ports:
      - "3000:3000"
    env_file:
      - .env
  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
    volumes:
      - .:/app
    command: bundle exec rspec